[package]
name = "nagetier"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
litrs = "1.0.0"
naga = { version = "28.0.0", features = ["wgsl-in", "stderr"] }
quote = "1.0.28"

[dev-dependencies]
wgpu = "0.16.0"
